USE [master]
GO
/****** Object:  Database [STORE]    Script Date: 8/14/2025 10:14:15 AM ******/
CREATE DATABASE [STORE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'STORE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.STORE\MSSQL\DATA\STORE.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'STORE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.STORE\MSSQL\DATA\STORE_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [STORE] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [STORE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [STORE] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [STORE] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [STORE] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [STORE] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [STORE] SET ARITHABORT OFF 
GO
ALTER DATABASE [STORE] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [STORE] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [STORE] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [STORE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [STORE] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [STORE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [STORE] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [STORE] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [STORE] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [STORE] SET  DISABLE_BROKER 
GO
ALTER DATABASE [STORE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [STORE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [STORE] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [STORE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [STORE] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [STORE] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [STORE] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [STORE] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [STORE] SET  MULTI_USER 
GO
ALTER DATABASE [STORE] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [STORE] SET DB_CHAINING OFF 
GO
ALTER DATABASE [STORE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [STORE] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [STORE] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [STORE] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [STORE] SET QUERY_STORE = ON
GO
ALTER DATABASE [STORE] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [STORE]
GO
/****** Object:  User [tamaisme]    Script Date: 8/14/2025 10:14:15 AM ******/
CREATE USER [tamaisme] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  User [bruh]    Script Date: 8/14/2025 10:14:15 AM ******/
CREATE USER [bruh] FOR LOGIN [bruh] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [tamaisme]
GO
ALTER ROLE [db_accessadmin] ADD MEMBER [tamaisme]
GO
ALTER ROLE [db_securityadmin] ADD MEMBER [tamaisme]
GO
ALTER ROLE [db_ddladmin] ADD MEMBER [tamaisme]
GO
ALTER ROLE [db_backupoperator] ADD MEMBER [tamaisme]
GO
ALTER ROLE [db_datareader] ADD MEMBER [tamaisme]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [tamaisme]
GO
ALTER ROLE [db_denydatareader] ADD MEMBER [tamaisme]
GO
ALTER ROLE [db_denydatawriter] ADD MEMBER [tamaisme]
GO
ALTER ROLE [db_owner] ADD MEMBER [bruh]
GO
ALTER ROLE [db_ddladmin] ADD MEMBER [bruh]
GO
ALTER ROLE [db_datareader] ADD MEMBER [bruh]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [bruh]
GO
/****** Object:  Table [dbo].[GIOHANG]    Script Date: 8/14/2025 10:14:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GIOHANG](
	[id_giohang] [int] IDENTITY(1,1) NOT NULL,
	[id_user] [varchar](50) NULL,
	[id_khach_hang] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_giohang] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GIOHANGCHITIET]    Script Date: 8/14/2025 10:14:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GIOHANGCHITIET](
	[id_giohang] [int] NOT NULL,
	[id_sanpham] [int] NOT NULL,
	[soluong] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_giohang] ASC,
	[id_sanpham] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOADON]    Script Date: 8/14/2025 10:14:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOADON](
	[id_hoadon] [int] IDENTITY(1,1) NOT NULL,
	[ngaytao] [date] NOT NULL,
	[trangthai] [varchar](30) NOT NULL,
	[diachi] [nvarchar](50) NOT NULL,
	[giaohang] [nvarchar](max) NULL,
	[id_user] [varchar](50) NULL,
	[id_khach_hang] [varchar](50) NULL,
	[discount_percent] [int] NULL,
	[discount_amount] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id_hoadon] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOADONCHITIET]    Script Date: 8/14/2025 10:14:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOADONCHITIET](
	[id_hoadon] [int] NOT NULL,
	[id_sanpham] [int] NOT NULL,
	[soluong] [int] NOT NULL,
	[giamgia] [int] NULL,
	[gia] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_hoadon] ASC,
	[id_sanpham] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHACH_HANG]    Script Date: 8/14/2025 10:14:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACH_HANG](
	[id_khach_hang] [bigint] IDENTITY(1,1) NOT NULL,
	[hoten] [varchar](255) NOT NULL,
	[sdt] [varchar](10) NOT NULL,
	[email] [varchar](255) NULL,
	[dia_chi] [varchar](255) NULL,
	[trang_thai] [bit] NOT NULL,
	[phan_loai] [nvarchar](255) NULL,
	[di_ung] [nvarchar](255) NULL,
	[chong_chi_dinh] [nvarchar](255) NULL,
	[ghi_chu_y_te] [nvarchar](500) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_khach_hang] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOAI]    Script Date: 8/14/2025 10:14:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOAI](
	[id_loai] [int] IDENTITY(1,1) NOT NULL,
	[ten_loai] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_loai] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHAN_VIEN]    Script Date: 8/14/2025 10:14:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHAN_VIEN](
	[id_nhan_vien] [varchar](50) NOT NULL,
	[hoten] [varchar](255) NOT NULL,
	[sdt] [varchar](10) NOT NULL,
	[email] [varchar](255) NULL,
	[dia_chi] [varchar](255) NULL,
	[trang_thai] [bit] NOT NULL,
	[luong] [decimal](18, 2) NULL,
	[ca_lam_viec] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_nhan_vien] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NOTIFICATION]    Script Date: 8/14/2025 10:14:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOTIFICATION](
	[id_notification] [int] IDENTITY(1,1) NOT NULL,
	[id_user] [varchar](50) NULL,
	[title] [nvarchar](255) NOT NULL,
	[content] [nvarchar](max) NOT NULL,
	[is_read] [bit] NOT NULL,
	[created_at] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_notification] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SANPHAM]    Script Date: 8/14/2025 10:14:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SANPHAM](
	[id_sanpham] [int] IDENTITY(1,1) NOT NULL,
	[ten_sanpham] [nvarchar](255) NOT NULL,
	[soluong] [int] NOT NULL,
	[hinh] [varchar](255) NULL,
	[mota] [nvarchar](max) NOT NULL,
	[motangan] [nvarchar](max) NULL,
	[gia] [int] NOT NULL,
	[giamgia] [int] NOT NULL,
	[ngaytao] [date] NOT NULL,
	[id_loai] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id_sanpham] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERS]    Script Date: 8/14/2025 10:14:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS](
	[id_user] [varchar](50) NOT NULL,
	[sdt] [varchar](10) NOT NULL,
	[hinh] [varchar](255) NULL,
	[hoten] [nvarchar](50) NOT NULL,
	[matkhau] [varchar](60) NOT NULL,
	[kichhoat] [bit] NOT NULL,
	[vaitro] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_user] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_HOADON_ID_KHACH_HANG]    Script Date: 8/14/2025 10:14:15 AM ******/
CREATE NONCLUSTERED INDEX [IX_HOADON_ID_KHACH_HANG] ON [dbo].[HOADON]
(
	[id_khach_hang] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_KHACH_HANG_SDT]    Script Date: 8/14/2025 10:14:15 AM ******/
CREATE NONCLUSTERED INDEX [IX_KHACH_HANG_SDT] ON [dbo].[KHACH_HANG]
(
	[sdt] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NOTIFICATION] ADD  DEFAULT ((0)) FOR [is_read]
GO
ALTER TABLE [dbo].[NOTIFICATION] ADD  DEFAULT (getdate()) FOR [created_at]
GO
ALTER TABLE [dbo].[GIOHANG]  WITH CHECK ADD FOREIGN KEY([id_user])
REFERENCES [dbo].[USERS] ([id_user])
GO
ALTER TABLE [dbo].[GIOHANGCHITIET]  WITH CHECK ADD FOREIGN KEY([id_giohang])
REFERENCES [dbo].[GIOHANG] ([id_giohang])
GO
ALTER TABLE [dbo].[GIOHANGCHITIET]  WITH CHECK ADD FOREIGN KEY([id_sanpham])
REFERENCES [dbo].[SANPHAM] ([id_sanpham])
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD FOREIGN KEY([id_user])
REFERENCES [dbo].[USERS] ([id_user])
GO
ALTER TABLE [dbo].[HOADONCHITIET]  WITH CHECK ADD FOREIGN KEY([id_hoadon])
REFERENCES [dbo].[HOADON] ([id_hoadon])
GO
ALTER TABLE [dbo].[HOADONCHITIET]  WITH CHECK ADD FOREIGN KEY([id_sanpham])
REFERENCES [dbo].[SANPHAM] ([id_sanpham])
GO
ALTER TABLE [dbo].[NOTIFICATION]  WITH CHECK ADD FOREIGN KEY([id_user])
REFERENCES [dbo].[USERS] ([id_user])
GO
ALTER TABLE [dbo].[SANPHAM]  WITH CHECK ADD FOREIGN KEY([id_loai])
REFERENCES [dbo].[LOAI] ([id_loai])
GO
USE [master]
GO
ALTER DATABASE [STORE] SET  READ_WRITE 
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[VOUCHER]') AND type in (N'U'))
BEGIN
	CREATE TABLE [dbo].[VOUCHER](
		[id_voucher] INT IDENTITY(1,1) NOT NULL,
		[code] VARCHAR(50) NOT NULL,
		[type] VARCHAR(20) NOT NULL, -- PERCENT or FIXED
		[value] DECIMAL(18,2) NOT NULL,
		[max_discount] DECIMAL(18,2) NULL,
		[min_order_value] DECIMAL(18,2) NULL,
		[usage_limit] INT NULL,
		[usage_per_user] INT NULL,
		[total_used] INT NOT NULL DEFAULT 0,
		[start_date] DATETIME NULL,
		[end_date] DATETIME NULL,
		[active] BIT NOT NULL DEFAULT 1,
		CONSTRAINT PK_VOUCHER PRIMARY KEY CLUSTERED ([id_voucher] ASC)
	);
	CREATE UNIQUE INDEX UX_VOUCHER_CODE ON [dbo].[VOUCHER]([code]);
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[VOUCHER_USAGE]') AND type in (N'U'))
BEGIN
	CREATE TABLE [dbo].[VOUCHER_USAGE](
		[id_usage] INT IDENTITY(1,1) NOT NULL,
		[id_voucher] INT NOT NULL,
		[id_user] VARCHAR(50) NOT NULL,
		[id_hoadon] INT NULL,
		[used_at] DATETIME NOT NULL DEFAULT GETDATE(),
		CONSTRAINT PK_VOUCHER_USAGE PRIMARY KEY CLUSTERED ([id_usage] ASC)
	);
	CREATE INDEX IX_VOUCHER_USAGE_VOUCHER_USER ON [dbo].[VOUCHER_USAGE]([id_voucher],[id_user]);
	ALTER TABLE [dbo].[VOUCHER_USAGE]  WITH CHECK ADD  CONSTRAINT FK_VOUCHER_USAGE_VOUCHER FOREIGN KEY([id_voucher]) REFERENCES [dbo].[VOUCHER] ([id_voucher]);
	ALTER TABLE [dbo].[VOUCHER_USAGE]  WITH CHECK ADD  CONSTRAINT FK_VOUCHER_USAGE_USERS FOREIGN KEY([id_user]) REFERENCES [dbo].[USERS] ([id_user]);
	ALTER TABLE [dbo].[VOUCHER_USAGE]  WITH CHECK ADD  CONSTRAINT FK_VOUCHER_USAGE_HOADON FOREIGN KEY([id_hoadon]) REFERENCES [dbo].[HOADON] ([id_hoadon]);
END
GO

/* Extend HOADON for voucher linkage if columns not present */
IF COL_LENGTH('dbo.HOADON','voucher_code') IS NULL
	ALTER TABLE [dbo].[HOADON] ADD [voucher_code] VARCHAR(50) NULL;
GO
IF COL_LENGTH('dbo.HOADON','voucher_discount_amount') IS NULL
	ALTER TABLE [dbo].[HOADON] ADD [voucher_discount_amount] DECIMAL(18,2) NULL;
GO
IF COL_LENGTH('dbo.HOADON','id_voucher') IS NULL
BEGIN
	ALTER TABLE [dbo].[HOADON] ADD [id_voucher] INT NULL;
	ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD  CONSTRAINT FK_HOADON_VOUCHER FOREIGN KEY([id_voucher]) REFERENCES [dbo].[VOUCHER] ([id_voucher]);
END
GO

